### ISSUE TITLE
Upgrade to support Swift Ocata / Keystone v3

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/obsolete-fedora3-swift-jms#1]
The JClouds library used in this project does not support Keystone v3 (see [this discussion](http://comments.gmane.org/gmane.comp.java.jenkins.user/36295) and [this issue](https://issues.apache.org/jira/browse/JCLOUDS-114). ) It looks like we need an alternative to JClouds.

**Comment by jefferya** [comment]
Production code uses https://github.com/ualbertalib/era-openstack-migration, issued created https://github.com/ualbertalib/era-openstack-migration/issues/2
